
<script type="text/javascript" src="../js/crawler.js"></script>
<div class="marquee" id="mycrawler">
  A vast range of ebooks from the world's leading academic, popular and professional publishers</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
</div>
Latest ebooks 
<script type="text/javascript">
marqueeInit({
	uniqueid: 'mycrawler',
	style: {
		'padding': '0px',
		'width': '545px',
				},
	inc: 8, //speed - pixel increment for each iteration of this marquee's movement
	mouse: 'cursor driven', //mouseover behavior ('pause' 'cursor driven' or false)
	moveatleast: 4,
	neutral: 200,
	savedirection: true
});
</script>



<div class="marquee" id="mycrawler2">
  <p>
  <img src="images/123.jpg" /> 
</p>
</div>

<script type="text/javascript">
marqueeInit({
	uniqueid: 'mycrawler2',
	style: {
		'padding': '5px',
		'width': '545px',
		'height': '180px'
	},
	inc: 10, //speed - pixel increment for each iteration of this marquee's movement
	mouse: 'cursor driven', //mouseover behavior ('pause' 'cursor driven' or false)
	moveatleast: 2,
	neutral: 150,
	savedirection: true,
	random: true
});
</script>